Added "make test" capability to command-line makefiles.

diff --git a/current/Makefile.in b/current/Makefile.in
--- a/current/Makefile.in
+++ b/current/Makefile.in
@@ -303,6 +303,67 @@ lib:
 bin: 
 	@mkdir -p bin
 
+test: bin/CppUnitTest$(EXEEXT) bin/CppGuiUnitTestEventSimulation$(EXEEXT) bin/CppGuiUnitCapturePlusEmit$(EXEEXT) $(__VTKUnitTest___depname)
+	@failed=0; all=0; xfail=0; xpass=0; skip=0; ws='[	 ]'; \
+	for tst in  bin/CppUnitTest$(EXEEXT) bin/CppGuiUnitTestEventSimulation$(EXEEXT) bin/CppGuiUnitCapturePlusEmit$(EXEEXT) bin/VTKUnitTest$(EXEEXT); do \
+	if $$tst; then \
+	all=`expr $$all + 1`; \
+	case "  " in \
+	*$$ws$$tst$$ws*) \
+	xpass=`expr $$xpass + 1`; \
+	failed=`expr $$failed + 1`; \
+	echo "XPASS: $$tst"; \
+	;; \
+	*) \
+	echo "PASS: $$tst"; \
+	;; \
+	esac; \
+	elif test $$? -ne 77; then \
+	all=`expr $$all + 1`; \
+	case "  " in \
+	*$$ws$$tst$$ws*) \
+	xfail=`expr $$xfail + 1`; \
+	echo "XFAIL: $$tst"; \
+	;; \
+	*) \
+	failed=`expr $$failed + 1`; \
+	echo "FAIL: $$tst"; \
+	;; \
+	esac; \
+	else \
+	skip=`expr $$skip + 1`; \
+	echo "SKIP: $$tst"; \
+	fi; \
+	done ; \
+	if test "$$failed" -eq 0; then \
+	if test "$$xfail" -eq 0; then \
+	banner="All $$all tests passed"; \
+	else \
+	banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	fi; \
+	else \
+	if test "$$xpass" -eq 0; then \
+	banner="$$failed of $$all tests failed"; \
+	else \
+	banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	fi; \
+	fi; \
+	dashes="$$banner"; \
+	skipped=""; \
+	if test "$$skip" -ne 0; then \
+	skipped="($$skip tests were not run)"; \
+	test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
+	dashes="$$skipped"; \
+	fi; \
+	report=""; \
+	dashes=`echo "$$dashes" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	test -z "$$skipped" || echo "$$skipped"; \
+	test -z "$$report" || echo "$$report"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0;
+
 lib/$(LIBPREFIX)wxGuiTesting$(WX3RDPARTYLIBPOSTFIX)$(LIBEXT): $(WXGUITESTING_OBJECTS)
 	rm -f $@
 	$(AR) $(AROPTIONS) $@ $(WXGUITESTING_OBJECTS)
diff --git a/current/build/msw/makefile.vc b/current/build/msw/makefile.vc
--- a/current/build/msw/makefile.vc
+++ b/current/build/msw/makefile.vc
@@ -1,6 +1,6 @@
 # =========================================================================
 #     This makefile was generated by
-#     Bakefile 0.2.3 (http://www.bakefile.org)
+#     Bakefile 0.2.5 (http://www.bakefile.org)
 #     Do not modify, all changes will be overwritten!
 # =========================================================================
 
@@ -195,6 +195,18 @@ __WXLIB_GL_NAME_p = wxmsw$(WX_VERSION)d_gl.lib
 !if "$(WX_DEBUG)" == "1" && "$(WX_MONOLITHIC)" == "0" && "$(WX_UNICODE)" == "1"
 __WXLIB_GL_NAME_p = wxmsw$(WX_VERSION)ud_gl.lib
 !endif
+!if "$(WX_DEBUG)" == "0" && "$(WX_MONOLITHIC)" == "0" && "$(WX_UNICODE)" == "0"
+__WXLIB_RICHTEXT_NAME_p = wxmsw$(WX_VERSION)_richtext.lib
+!endif
+!if "$(WX_DEBUG)" == "0" && "$(WX_MONOLITHIC)" == "0" && "$(WX_UNICODE)" == "1"
+__WXLIB_RICHTEXT_NAME_p = wxmsw$(WX_VERSION)u_richtext.lib
+!endif
+!if "$(WX_DEBUG)" == "1" && "$(WX_MONOLITHIC)" == "0" && "$(WX_UNICODE)" == "0"
+__WXLIB_RICHTEXT_NAME_p = wxmsw$(WX_VERSION)d_richtext.lib
+!endif
+!if "$(WX_DEBUG)" == "1" && "$(WX_MONOLITHIC)" == "0" && "$(WX_UNICODE)" == "1"
+__WXLIB_RICHTEXT_NAME_p = wxmsw$(WX_VERSION)ud_richtext.lib
+!endif
 !if "$(WX_DEBUG)" == "0"
 __OPT = /O2
 !endif
@@ -388,6 +400,68 @@ test_for_selected_wxbuild:
 	@if not exist $(WX_DIR)$(WXLIBPATH)\msw$(WXLIBPOSTFIX)\wx\setup.h \
 	exit 1
 
+test: ..\..\bin\CppUnitTest.exe ..\..\bin\CppGuiUnitTestEventSimulation.exe ..\..\bin\CppGuiUnitCapturePlusEmit.exe $(__VTKUnitTest___depname)
+	@echo off\
+	failed=0; all=0; xfail=0; xpass=0; skip=0; ws='[	 ]'; \
+	for tst in ( ..\..\bin/CppUnitTest.exe ..\..\bin/CppGuiUnitTestEventSimulation.exe ..\..\bin/CppGuiUnitCapturePlusEmit.exe ..\..\bin/VTKUnitTest.exe); do \
+	if %tst%; then \
+	all=`expr %all% + 1`; \
+	case "  " in \
+	*%ws$$tst$$ws%*) \
+	xpass=`expr %xpass% + 1`; \
+	failed=`expr %failed% + 1`; \
+	echo "XPASS: %tst%"; \
+	;; \
+	*) \
+	echo "PASS: %tst%"; \
+	;; \
+	esac; \
+	elif test $$? -ne 77; then \
+	all=`expr %all% + 1`; \
+	case "  " in \
+	*%ws$$tst$$ws%*) \
+	xfail=`expr %xfail% + 1`; \
+	echo "XFAIL: %tst%"; \
+	;; \
+	*) \
+	failed=`expr %failed% + 1`; \
+	echo "FAIL: %tst%"; \
+	;; \
+	esac; \
+	else \
+	skip=`expr %skip% + 1`; \
+	echo "SKIP: %tst%"; \
+	fi; \
+	done ; \
+	if test "%failed%" -eq 0; then \
+	if test "%xfail%" -eq 0; then \
+	banner="All %all% tests passed"; \
+	else \
+	banner="All %all% tests behaved as expected (%xfail% expected failures)"; \
+	fi; \
+	else \
+	if test "%xpass%" -eq 0; then \
+	banner="%failed% of %all% tests failed"; \
+	else \
+	banner="%failed% of %all% tests did not behave as expected (%xpass% unexpected passes)"; \
+	fi; \
+	fi; \
+	dashes="%banner%"; \
+	skipped=""; \
+	if test "%skip%" -ne 0; then \
+	skipped="(%skip% tests were not run)"; \
+	test `echo "%skipped%" | wc -c` -le `echo "%banner%" | wc -c` || \
+	dashes="%skipped%"; \
+	fi; \
+	report=""; \
+	dashes=`echo "%dashes%" | sed s/./=/g`; \
+	echo "%dashes%"; \
+	echo "%banner%"; \
+	test -z "%skipped%" || echo "%skipped%"; \
+	test -z "%report%" || echo "%report%"; \
+	echo "%dashes%"; \
+	test "%failed%" -eq 0;
+
 ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib: $(WXGUITESTING_OBJECTS)
 	if exist $@ del $@
 	link /LIB /NOLOGO /OUT:$@ @<<
@@ -395,33 +469,33 @@ test_for_selected_wxbuild:
 <<
 
 ..\..\bin\CppUnitTest.exe: $(CPPUNITTEST_OBJECTS) ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib
-	link /NOLOGO /OUT:$@ $(LDFLAGS) /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppUnitTest.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE @<<
-	$(CPPUNITTEST_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
+	link /NOLOGO /OUT:$@  /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppUnitTest.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE $(LDFLAGS) @<<
+	$(CPPUNITTEST_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_RICHTEXT_NAME_p) $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
 <<
 
 ..\..\bin\CppGuiUnitTestEventSimulation.exe: $(CPPGUIUNITTESTEVENTSIMULATION_OBJECTS) ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib
-	link /NOLOGO /OUT:$@ $(LDFLAGS) /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppGuiUnitTestEventSimulation.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE @<<
-	$(CPPGUIUNITTESTEVENTSIMULATION_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
+	link /NOLOGO /OUT:$@  /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppGuiUnitTestEventSimulation.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE $(LDFLAGS) @<<
+	$(CPPGUIUNITTESTEVENTSIMULATION_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_RICHTEXT_NAME_p) $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
 <<
 
 ..\..\bin\CppGuiUnitTestCaptureReplay.exe: $(CPPGUIUNITTESTCAPTUREREPLAY_OBJECTS) ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib
-	link /NOLOGO /OUT:$@ $(LDFLAGS) /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppGuiUnitTestCaptureReplay.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE @<<
-	$(CPPGUIUNITTESTCAPTUREREPLAY_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
+	link /NOLOGO /OUT:$@  /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppGuiUnitTestCaptureReplay.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE $(LDFLAGS) @<<
+	$(CPPGUIUNITTESTCAPTUREREPLAY_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_RICHTEXT_NAME_p) $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
 <<
 
 ..\..\bin\CppGuiUnitTestModalDialog.exe: $(CPPGUIUNITTESTMODALDIALOG_OBJECTS) ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib
-	link /NOLOGO /OUT:$@ $(LDFLAGS) /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppGuiUnitTestModalDialog.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE @<<
-	$(CPPGUIUNITTESTMODALDIALOG_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
+	link /NOLOGO /OUT:$@  /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppGuiUnitTestModalDialog.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE $(LDFLAGS) @<<
+	$(CPPGUIUNITTESTMODALDIALOG_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_RICHTEXT_NAME_p) $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
 <<
 
 ..\..\bin\CppGuiUnitCapturePlusEmit.exe: $(CPPGUIUNITCAPTUREPLUSEMIT_OBJECTS) ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib
-	link /NOLOGO /OUT:$@ $(LDFLAGS) /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppGuiUnitCapturePlusEmit.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE @<<
-	$(CPPGUIUNITCAPTUREPLUSEMIT_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
+	link /NOLOGO /OUT:$@  /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\CppGuiUnitCapturePlusEmit.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /SUBSYSTEM:CONSOLE $(LDFLAGS) @<<
+	$(CPPGUIUNITCAPTUREPLUSEMIT_OBJECTS)  $(CPPUNIT_LIB).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib $(__WXLIB_RICHTEXT_NAME_p) $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
 <<
 
 !if "$(USE_VTK)" == "1"
 ..\..\bin\VTKUnitTest.exe: $(VTKUNITTEST_OBJECTS) ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib
-	link /NOLOGO /OUT:$@ $(LDFLAGS) /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\VTKUnitTest.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /LIBPATH:$(VTK_LIBDIR) /SUBSYSTEM:CONSOLE @<<
+	link /NOLOGO /OUT:$@  /LIBPATH:$(CPPUNIT_LIBDIR) $(__DBG_10) /pdb:"..\..\bin\VTKUnitTest.pdb" /LIBPATH:$(WX_DIR)$(WXLIBPATH) /LIBPATH:$(VTK_LIBDIR) /SUBSYSTEM:CONSOLE $(LDFLAGS) @<<
 	$(VTKUNITTEST_OBJECTS)  $(CPPUNIT_LIB).lib vtkCommon.lib vtkDICOMParser.lib vtkexpat.lib vtkFiltering.lib vtkfreetype.lib vtkftgl.lib vtkGraphics.lib vtkHybrid.lib vtkImaging.lib vtkIO.lib vtkjpeg.lib vtkpng.lib vtkRendering.lib vtktiff.lib vtkzlib.lib ..\..\lib\wxGuiTesting$(WX3RDPARTYLIBPOSTFIX).lib opengl32.lib glu32.lib $(__WXLIB_GL_NAME_p) $(__WXLIB_XRC_NAME_p) $(__WXLIB_HTML_NAME_p) $(__WXLIB_ADV_NAME_p) $(__WXLIB_XML_NAME_p) $(__WXLIB_CORE_NAME_p) $(__WXLIB_BASE_NAME_p) wxtiff$(WX3RDPARTYLIBPOSTFIX).lib wxjpeg$(WX3RDPARTYLIBPOSTFIX).lib wxpng$(WX3RDPARTYLIBPOSTFIX).lib wxzlib$(WX3RDPARTYLIBPOSTFIX).lib wxregex$(WXLIBPOSTFIX).lib wxexpat$(WX3RDPARTYLIBPOSTFIX).lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib wsock32.lib oleacc.lib
 <<
 !endif
